### PR TITLE
Calendar US007 AC 1-2-3

### PR DESCRIPTION
**Pull request by Osman-oguz**
Created CalendarPage, Calendar_OO.feature, CalendarStepDefs for the 1-2-3 AC
PLease check :)

### CODE REVIEW

**Comment by msarpcelik** [comment]
Great job!

**Review by msarpcelik — COMMENTED** [review]
Great!

**Review by msarpcelik — APPROVED** [review]
Everything is cool! Great job.

**Comment by Osman-oguz** [comment]
Thanks.

**Pull request merged**
